export const AuthConfig = {
	PASSWORD_SALT_ROUND: 10,
	EMAIL_REGEX: /^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$/,
	TOKEN_KEY: "nekot",
	TOKEN_EXPIRE_TIME: 3600000,
	REGISTER_SUCCESS_MESSAGE: "User created successfully",
	REQUIRED_FIELD_MISSING: "Required fields not found",
	DUPLICATE_USER: "User already registered",
	USER_NOT_FOUND: "User not found",
	INVALID_EMAIL: "Invalid email id",
	WRONG_CREDENTIALS: "Wrong Email id or Password",
	LOGIN_SUCCESS: "User login success",
	OTP_SEND_FAILED: "There was some issue while sending the OTP.",
	OTP_SENT_SUCCESS: "OTP sent successfully on given e-mail",
	OTP_MISMATCHED: "Invalid OTP or OTP expired",
	OTP_MATCHED: "OTP matched",
	PASSWORD_RESET_SUCCESS: "Password changed successfully",
	LOGOUT_SUCCESS: "Logout Successful",
};
